# Limits for the Pilz planner
# Warning: These limits have not been verified. Package not tested with Pilz
cartesian_limits:
  max_trans_vel: 1.0
  max_trans_acc: 2.25
  max_trans_dec: -5.0
  max_rot_vel: 1.57
