controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    fer_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

fer_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
    gains:
      fer_joint1: { p: 100.0, d: 20.0, i: 0.0, i_clamp: 1.0 }
      fer_joint2: { p: 100.0, d: 20.0, i: 0.0, i_clamp: 1.0 }
      fer_joint3: { p: 100.0, d: 20.0, i: 0.0, i_clamp: 1.0 }
      fer_joint4: { p: 100.0, d: 20.0, i: 0.0, i_clamp: 1.0 }
      fer_joint5: { p: 50.0, d: 10.0, i: 0.0, i_clamp: 1.0 }
      fer_joint6: { p: 35.0, d: 10.0, i: 0.0, i_clamp: 1.0 }
      fer_joint7: { p: 10.0, d: 5.0, i: 0.0, i_clamp: 1.0 }
    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.1
      fer_joint1: {trajectory: 0.8, goal: 0.05}
      fer_joint2: {trajectory: 0.8, goal: 0.05}
      fer_joint3: {trajectory: 0.8, goal: 0.05}
      fer_joint4: {trajectory: 0.8, goal: 0.05}
      fer_joint5: {trajectory: 0.8, goal: 0.05}
      fer_joint6: {trajectory: 0.8, goal: 0.05}
      fer_joint7: {trajectory: 0.8, goal: 0.05}
    allow_partial_joints_goal: true
    allow_nonzero_velocity_at_trajectory_end: true ##### ABSOLUTELY FUCKING CRITICAL #####
    # Key parameter for servo applications
    open_loop_control: true
    # Additional parameters for smoother servo behavior
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    hold_trajectory_duration: 0.0
    allow_integration_in_goal_trajectories: true
    interpolation_method: "splines"
    interpolate_from_desired_state: true

joint_state_broadcaster:
    ros__parameters:
        use_local_topics: true